{
 "title": "Monitoramento de Rede",
 "tags": [
  "network",
  "monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "site",
    "query": "SELECT DISTINCT site FROM network_test_results"
   }
  ]
 },
 "panels": [
  {
   "title": "Latência (ms) por Site",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", latency FROM network_test_results WHERE $__timeFilter(timestamp) AND site = '$site' ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Perda de Pacotes (%) por Site",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", packet_loss FROM network_test_results WHERE $__timeFilter(timestamp) AND site = '$site' ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Evolução dos Códigos HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", status_code::text AS metric, status_code FROM network_test_results WHERE $__timeFilter(timestamp) AND site = '$site' ORDER BY timestamp"
    }
   ]
  }
 ]
}